baseURL = 'https://hugo-roan-six.vercel.app/'
languageCode = 'en-us'
title = 'Muhamad Aliyudin'

disqusShortname = 'Aliyudin'   # use disqus comments

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'Malydn20'               # twitter.com/YOUR_TWITTER_ID
  instagram = 'alydn2/'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'muhamad-aliyudin-b5b16620b/'             # linkedin.com/in/YOUR_LINKEDIN_ID



  # home page profile
  avatar = ''                 # gravatar email or image url
  name = 'Muhamad Aliyudin'
  bio = 'Blogger'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "Alydn"  # use graph comment (disqus alternative)
  math = false                               # enable KaTex math typesetting globally
  